import HeroImage from "@/components/auth/HeroImage";
import Button2 from "@/components/auth/BtnSecondary";
import LogInForm from "@/components/auth/LogInForm";

export const metadata = {
  title: "Unstop Login",
  description: "Generated by create next app",
};

export default function Login() {
  return (
    <div className="bg-[#F4F4F4] h-screen flex">
      <div className="h-svh w-[50%] justify-center items-center hidden md:flex">
        <HeroImage />
      </div>
      <div className="h-svh w-[100%]  md:w-[50%] flex justify-center items-center">
        <div className="bg-[#FFFFFF] flex flex-col w-[95%] md:w-[95%] h-[90%] overflow-scroll rounded-[20px] font-[500] py-[30px] px-[35px] border-[1px] gap-6 border-[#E2E2E2] justify-between">
          <span className="heading-text">
            Welcome to <br />
            <span className="text-[#6358DC] unstop">Unstop</span>
          </span>
          <div className="flex flex-col gap-[16px]">
            <Button2 title="Login with Google" imgsrc={"/googleicon.svg"} />
            <Button2 title="Login with Facebook" imgsrc={"/facebookicon.svg"} />
          </div>
          <div className="flex items-center w-full">
            <hr className="flex-grow border-t border-gray-300" />
            <span className="mx-4 text-gray-600 tracking-widest font-[400] text-[16px]">
              OR
            </span>
            <hr className="flex-grow border-t border-gray-300" />
          </div>
          <div>
            <LogInForm />
          </div>
        </div>

        <div></div>
      </div>
    </div>
  );
}
